services:
    gmt-playwright-nodejs:
        image: mcr.microsoft.com/playwright:v1.58.0-noble
#        volumes:
#            - /tmp/.X11-unix:/tmp/.X11-unix # for debugging in non-headless mode
#        environment:
#            DISPLAY: ":0" # for debugging in non-headless mode
        setup-commands:
            # install playwright libraries in writeable directory
            - command: cd /tmp/gmt-utils && npm init -y && npm install playwright@1.58.0
              shell: bash
        # playwright-ipc.js will be mounted into container via lib/scenario_runner.py to not conflict with include directory restrictions

    squid:
        image: greencoding/squid_reverse_proxy:v5
        healthcheck:
            test: ["CMD", "curl", "-fs", "--proxy", "http://squid:3128", "https://www.google.com", "--insecure"]
            interval: "1h" # effectively turns repeated healthchecks during runtime off
            start_period: "60s"
            start_interval: "1s"
# activate for debugging
#        ports:
#           - 3128:3128

flow-prepend:
  - name: Starting browser IPC
    container: gmt-playwright-nodejs
    hidden: true
    commands:
      - type: console
        command: node /tmp/gmt-utils/gmt-playwright-ipc.js --headless true --browser firefox --proxy http://squid:3128
        note: Starting browser in background process with IPC
        detach: true
      - type: console
        command: timeout 5 bash -c 'until [ -p "/tmp/playwright-ipc-ready" ]; do sleep 1; done && echo "Browser ready!"'
        shell: bash
        note: Waiting for website stepper loop to start by monitoring rendezvous file endpoint
