ALTER TABLE measurements
ALTER COLUMN project_id SET NOT NULL,
ALTER COLUMN detail_name SET NOT NULL,
ALTER COLUMN metric SET NOT NULL,
ALTER COLUMN value SET NOT NULL,
ALTER COLUMN unit SET NOT NULL,
ALTER COLUMN time SET NOT NULL;


ALTER TABLE phase_stats
ALTER COLUMN project_id SET NOT NULL,
ALTER COLUMN detail_name SET NOT NULL,
ALTER COLUMN metric SET NOT NULL,
ALTER COLUMN value SET NOT NULL,
ALTER COLUMN unit SET NOT NULL,
ALTER COLUMN type SET NOT NULL,
ALTER COLUMN phase SET NOT NULL;
