CREATE TABLE network_connections_tcpdump (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id uuid NOT NULL REFERENCES runs(id) ON DELETE CASCADE ON UPDATE CASCADE,
    detail_name text NOT NULL,
    metric text NOT NULL,
    stats text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone
);
CREATE INDEX network_connections_tcpdump_run_id ON network_connections_tcpdump USING HASH (run_id);
CREATE TRIGGER network_connections_tcpdump_moddatetime
    BEFORE UPDATE ON network_connections_tcpdump
    FOR EACH ROW
    EXECUTE PROCEDURE moddatetime (updated_at);

ALTER TABLE network_intercepts RENAME TO network_connections_proxy;
ALTER TRIGGER network_intercepts_moddatetime ON network_connections_proxy RENAME TO network_connections_proxy_moddatetime;

UPDATE users
SET capabilities = jsonb_set(
    capabilities,
    '{api,routes}',
    ((capabilities->'api'->'routes') - '/v1/network/{run_id}' - '/v1/network/stats/{run_id}')
        || '"/v1/network/connections/proxy/{run_id}"'::jsonb
        || '"/v1/network/connections/tcpdump/{run_id}"'::jsonb
)
WHERE id = 1
    AND NOT (capabilities->'api'->'routes' ? '/v1/network/connections/proxy/{run_id}');
