CREATE TYPE job_state AS ENUM ('WAITING', 'PAUSED', 'CANCELLED', 'FINISHED', 'FAILED', 'RUNNING');

ALTER TABLE "jobs"
  ALTER COLUMN "state" TYPE job_state USING state::job_state,
  ALTER COLUMN "state" SET DEFAULT 'WAITING';