FROM python:3.12.5-slim-bookworm
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /var/www/startup/
COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install --upgrade pip
RUN --mount=type=cache,target=/root/.cache/pip venv/bin/pip install -r requirements.txt

# This sets the include path for python, so we can use a module like include syntax in our files
RUN find venv -type d -name "site-packages" -exec sh -c 'echo /var/www/green-metrics-tool > "$0/gmt-lib.pth"' {} \;

COPY startup_gunicorn.sh /var/www/startup/startup_gunicorn.sh

# even if this file does not exist it will still help by not creating
# a permission error when trying /root/.postgresql/postgresql.crt
ENV PGSSLCERT /tmp/postgresql.crt


ENTRYPOINT ["/bin/bash", "/var/www/startup/startup_gunicorn.sh"]
