name: 'GMT Pytest'
description:  'Run Pytest with setup and teardown'
inputs:
  metrics-to-turn-off:
    description: 'a list of metrics to turn off that is passed to the disable metrics script'
    required: false
    default: ''
  gmt-directory:
    description: 'The root directory of the gmt repository'
    required: false
    default: '.'
  tests-command:
    description: 'The command to run the tests'
    required: false
    default: 'pytest -vv --durations=0'
  test-path:
    description: 'Specific test path to run'
    required: false
    default: ''
  github-token:
    description: 'pass in your secrets.GITHUB_TOKEN'
    required: true
  ee:
    description: 'enable enterprise tests'
    required: false
    default: false
  ee-branch:
    description: 'Sets the branch to checkout for the ee repo'
    required: false
    default: ''
  enable-ssh:
    description: 'Enable SSH connection for debugging purposes'
    required: false
    default: 'false'


runs:
  using: 'composite'
  steps:
    - name: setup_python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - id: python_cache
      uses: actions/cache@v4
      with:
        path: venv
        key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('docker/requirements.txt') }}-${{ hashFiles('metric_providers/psu/energy/ac/xgboost/machine/model/requirements.txt') }}

    - name: install script and packages
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}
      run: |
        if ${{inputs.ee}}; then
          if [[ "${{inputs.ee-branch}}" != '' ]]; then
            echo "Using ee-branch ${{inputs.ee-branch}}"
            ./install_linux.sh -p testpw -a http://api.green-coding.internal:9142 -m http://metrics.green-coding.internal:9142 -B -T -L -z -f -j -d -g -e github-actions-test --ee-branch ${{inputs.ee-branch}} --nvidia-gpu --ai --tz GMT
          else
            ./install_linux.sh -p testpw -a http://api.green-coding.internal:9142 -m http://metrics.green-coding.internal:9142 -B -T -L -z -f -j -d -g -e github-actions-test --nvidia-gpu --ai --tz GMT
          fi
        else
          ./install_linux.sh -p testpw -a http://api.green-coding.internal:9142 -m http://metrics.green-coding.internal:9142 -B -T -L -z -f -j -d -g --nvidia-gpu --tz GMT
        fi
        source venv/bin/activate
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    # To save cache to packages
    # https://github.com/green-coding-solutions/green-metrics-tool/pkgs/container/gunicorn-container-cache/versions
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Install dev requirements and run test setup script
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}
      run: |
        source venv/bin/activate
        python3 -m pip install -r requirements-dev.txt
        playwright install --with-deps firefox
        export USE_GH_ACTIONS_CACHE='type=registry,ref=ghcr.io/green-coding-solutions/gunicorn-container-cache:cache'
        if ${{inputs.ee}}; then
          cd tests && python3 setup-test-env.py --ee
        else
          cd tests && python3 setup-test-env.py
        fi

    - name: Start Test container
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}/tests
      run: |
        source ../venv/bin/activate && ./start-test-containers.sh -d

    # for debugging purposes you can setup a ssh connection by setting 'inputs.enable-ssh' to true
    - name: Setup upterm session
      if: ${{ inputs.enable-ssh == 'true' }}
      uses: owenthereal/action-upterm@de23d094ff41be3a09894c4e2b8dd74378013f2e
      with:
        limit-access-to-actor: true # Restrict to the user who triggered the workflow

    - name: Disable swap
      shell: bash
      run: |
        sudo swapoff -a

    - name: Run Tests
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}/tests
      env:
        DEFAULT_TEST_PATH: ${{ inputs.test-path }}
      run: |
        source ../venv/bin/activate
        COMMIT_MSG="$(git log -1 --pretty=%B)"
        echo "Commit message:"
        echo "$COMMIT_MSG"

        if [[ "$COMMIT_MSG" =~ \[test-path:\ ([^]]+)\] ]]; then
          TEST_PATH="${BASH_REMATCH[1]}"
          echo "Detected test-path keyword: $TEST_PATH"
        else
          echo "No test keyword detected. Using default: ${{ inputs.test-path }}"
          TEST_PATH="${DEFAULT_TEST_PATH}"
        fi

        python3 -m ${{ inputs.tests-command }} "${TEST_PATH}" -rA | tee /tmp/test-results.txt

    - name: Display Results
      shell: bash
      if: always()
      run: |
        cat /tmp/test-results.txt | grep -oPz '(=*) short test summary(.*\n)*' >> $GITHUB_STEP_SUMMARY

    - name: Stop Containers
      shell: bash
      if: always()
      working-directory: ${{ inputs.gmt-directory }}/tests
      run: |
        ./stop-test-containers.sh
