name: 'GMT Pytest'
description:  'Run Pytest with setup and teardown'
inputs:
  metrics-to-turn-off:
    description: 'a list of metrics to turn off that is passed to the disable metrics script'
    required: false
    default: ''
  gmt-directory:
    description: 'The root directory of the gmt repository'
    required: false
    default: '.'
  tests-directory:
    description: 'The directory where to run the tests from'
    required: false
    default: './tests'
  tests-command:
    description: 'The command to run the tests'
    required: false
    default: 'pytest'
  github-token:
    description: 'pass in your secrets.GITHUB_TOKEN'
    required: true

runs:
  using: 'composite'
  steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: GMT setup
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}
      run: |
        ./install_linux.sh -p testpw -a http://api.green-coding.internal:9142 -m http://metrics.green-coding.internal:9142 -n -t -w
        source venv/bin/activate
        echo "DMM: DEBUG:"
        echo $VIRTUAL_ENV
        echo $(find venv -type f -path "*/site-packages/gmt-lib.pth")
        echo "DMM"
        pip install -r requirements-dev.txt
        pip install -r metric_providers/psu/energy/ac/xgboost/machine/model/requirements.txt
        python3 disable_metric_providers.py ${{ inputs.metrics-to-turn-off }}
        cd tests && python3 setup-test-env.py --no-docker-build
        echo "GMT setup complete"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build docker-compose
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}/docker
      run: docker buildx bake --file test-compose.yml --file docker-compose-cache.json

      # the working directory here is explicit, instead of using ${{ inputs.tests-directory }}
      # the reason for this is because ${{ inputs.tests-directory }} is mainly used by Examples Applications repo (which uses this action)
      # to run their tests, but they still need the GMT containers running

    - name: Start Test container
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}/tests
      run: |
        source ../venv/bin/activate && ./start-test-containers.sh -d
   
    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash
        
    - name: Run Tests
      shell: bash
      working-directory: ${{ inputs.tests-directory }}
      run: |
        echo "DMM: inputs.tests-directory:"
        echo ${{ inputs.tests-directory }}
        echo "DMM: DEBUG:"
        echo "DMM: Before source:"
        python -c "import sys; print(sys.executable, '\n', sys.path)"
        echo $VIRTUAL_ENV
        source ../venv/bin/activate
        echo "DMM: After source:"
        echo "DMM: python -c "import sys command:"
        python -c "import sys; print(sys.executable, '\n', sys.path)"
        echo "DMM: VIRTUAL_ENV:"
        echo $VIRTUAL_ENV
        echo "DMM: find gmt-lib path:"
        echo $(find ../venv -type f -path "*/site-packages/gmt-lib.pth")
        echo "DMM: cat gmt-lib.pth:"
        cat ../venv/lib/python3.10/site-packages/gmt-lib.pth
        echo "DMM"
        ${{ inputs.tests-command }} -rA | tee /tmp/test-results.txt

    - name: Display Results
      shell: bash
      if: always()
      working-directory: ${{ inputs.tests-directory }}
      run: |
        cat /tmp/test-results.txt | grep -oPz '(=*) short test summary(.*\n)*' >> $GITHUB_STEP_SUMMARY

    - name: Stop Containers
      shell: bash
      if: always()
      working-directory: ${{ inputs.gmt-directory }}/tests
      run: |
        ./stop-test-containers.sh
