name: 'GMT Pytest'
description:  'Run Pytest with setup and teardown'
inputs:
  metrics-to-turn-off:
    description: 'a list of metrics to turn off that is passed to the disable metrics script'
    required: false
    default: ''
  gmt-directory:
    description: 'The root directory of the gmt repository'
    required: false
    default: '.'
  run-examples-directory-tests:
    description: 'Run tests for examples directory instead of regular gmt tests'
    default: false
  github-token:
    description: 'pass in your secrets.GITHUB_TOKEN'
    required: true

runs:
  using: 'composite'
  steps:
    - name: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - id: python_cache
      uses: actions/cache@v3
      with:
        path: venv
        key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('metric_providers/psu/energy/ac/xgboost/machine/model/requirements.txt') }}

    - name: install script and packages
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}
      run: |
        ./install_linux.sh -p testpw -a http://api.green-coding.internal:9142 -m http://metrics.green-coding.internal:9142 -n -t
        source venv/bin/activate
        python3 -m pip install -r requirements-dev.txt
        python3 -m pip install -r metric_providers/psu/energy/ac/xgboost/machine/model/requirements.txt
      
    - name: disable unneeded metric providers and run test setup script
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}
      run: |
        source venv/bin/activate
        python3 disable_metric_providers.py ${{ inputs.metrics-to-turn-off }}
        cd tests && python3 setup-test-env.py --no-docker-build

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build docker-compose
      id: build-docker-compose
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}/docker
      run: |
        { DOCKER_OUTPUT=$(docker buildx bake --file test-compose.yml --file docker-compose-cache.json 2>&1); DOCKER_EXIT_CODE=$?; } || true
        if [ "$DOCKER_EXIT_CODE" -ne 0 ]; then
          echo "Docker build failed with exit code $DOCKER_EXIT_CODE"
          echo "buildx output:"
          echo $DOCKER_OUTPUT
          if echo "$DOCKER_OUTPUT" | grep -q "403 Forbidden"; then
            echo "Docker build failed due to permissions issue. Continuing..."
          else
              exit 1
          fi
        fi

    - name: Start Test container
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}/tests
      run: |
        source ../venv/bin/activate && ./start-test-containers.sh -d
   
    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash

    - name: Run Tests
      if: inputs.run-examples-directory-tests == 'false'
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}/tests
      run: |
        source ../venv/bin/activate
        python3 -m pytest -n auto -m "not serial" -rA | tee -a /tmp/test-results.txt
        python3 -m pytest -m "serial" -rA | tee -a /tmp/test-results.txt

    - name: Run Tests (examples directory)
      if: inputs.run-examples-directory-tests == 'true'
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}/tests
      run: |
        source ../venv/bin/activate
        python3 -m pytest ../../examples-directory/test/smoke_test.py -k "test_all_directories" -rA | tee -a /tmp/test-results.txt

    - name: Display Results
      shell: bash
      if: always()
      run: |
        cat /tmp/test-results.txt | grep -oPz '(=*) short test summary(.*\n)*' >> $GITHUB_STEP_SUMMARY

    - name: Stop Containers
      shell: bash
      if: always()
      working-directory: ${{ inputs.gmt-directory }}/tests
      run: |
        ./stop-test-containers.sh
