name: 'GMT Pytest'
description:  'Run Pytest with setup and teardown'
inputs:
  metrics-to-turn-off:
    description: 'a list of metrics to turn off that is passed to the disable metrics script'
    required: false
    default: ''
  gmt-directory:
    description: 'The root directory of the gmt repository'
    required: false
    default: '.'
  tests-command:
    description: 'The command to run the tests'
    required: false
    default: 'pytest -vv --durations=0'
  test-path:
    description: 'Specific test path to run'
    required: false
    default: ''
  github-token:
    description: 'pass in your secrets.GITHUB_TOKEN'
    required: true
  docker-user:
    description: 'pass in your secret for the Docker User to use for private repo clone tests'
    required: false
  docker-pat:
    description: 'pass in your secret for the Docker PAT to use for private repo clone tests'
    required: false
  ee:
    description: 'enable enterprise tests'
    required: false
    default: false
  ee-branch:
    description: 'Sets the branch to checkout for the ee repo'
    required: false
    default: ''
  enable-ssh:
    description: 'Enable SSH connection for debugging purposes'
    required: false
    default: 'false'


runs:
  using: 'composite'
  steps:

    - name: Debug
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}/tests
      env:
        DEFAULT_TEST_PATH: ${{ inputs.test-path }}
        GMT_TESTING_DOCKER_USER: ${{ inputs.docker-user }}
        GMT_TESTING_DOCKER_PAT: ${{ inputs.docker-pat }}
      run: |
        COMMIT_MSG="$(git log -1 --pretty=%B 2>&1)"
        echo "Commit message:"
        echo "$COMMIT_MSG"
        echo "$PWD"
        git rev-parse --show-toplevel
