name: 'GMT Pytest'
description:  'Run Pytest with setup and teardown'
inputs:
  metrics-to-turn-off:
    description: 'a list of metrics to turn off that is passed to the disable metrics script'
    required: false
    default: ''
outputs:
runs:
  using: 'composite'
  steps:
    - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pytest psycopg2 numpy pandas xgboost statsmodels scipy scikit-learn
      
      - name: Run Prereqs and Install Script
        run: |
          sudo apt install lm-sensors libsensors-dev libglib2.0-0 libglib2.0-dev
          ./install.sh -p testpw

      - name: Turn off metric providers which do not work in github vm
        run: |
          ./disable-metric-providers.sh ${{ metrics-to-turn-off }}

      - name: Setup Test environment
        working-directory: ./test
        run: |
          ./setup-test-env.sh -p testpw
          
      - name: Start Test container
        working-directory: ./test
        run: |
          docker compose -f ../docker/test-compose.yml up -d
     
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
          
      - name: Run Tests
        working-directory: ./test
        run: |
          pytest
          
      - name: Stop Containers
        if: always()
        working-directory: ./test
        run: |
          docker compose -f ../docker/test-compose.yml down -v