name: 'GMT Pytest'
description:  'Run Pytest with setup and teardown'
inputs:
  gmt-directory:
    description: 'The root directory of the gmt repository'
    required: false
    default: '.'
  tests-command:
    description: 'The command to run the tests'
    required: false
    default: 'pytest'
  github-token:
    description: 'pass in your secrets.GITHUB_TOKEN'
    required: true

runs:
  using: 'composite'
  steps:
    - name: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # - id: python_cache
    #   uses: actions/cache@v3
    #   with:
    #     path: venv
    #     key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('metric_providers/psu/energy/ac/xgboost/machine/model/requirements.txt') }}

    - name: Install docker for MacOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        bash -x ./install_mac.sh -p testpw -a http://api.green-coding.internal:9142 -m http://metrics.green-coding.internal:9142
        source venv/bin/activate && pip install -r requirements-dev.txt


    - name: Build test image and start test containers
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}
      run: |
        source ../venv/bin/activate && python3 setup-test-env.py
        source ../venv/bin/activate && ./start-test-containers.sh -d

    - name: Run Tests
      continue-on-error: true
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}
      run: |
         source ../venv/bin/activate && python3 -m pytest -rA

    - name: Stop Containers
      shell: bash
      if: always()
      working-directory: ${{ inputs.gmt-directory }}/tests
      run: |
        ./stop-test-containers.sh
