/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JobChange model module.
 * @module model/JobChange
 * @version 0.1.0
 */
class JobChange {
    /**
     * Constructs a new <code>JobChange</code>.
     * @alias module:model/JobChange
     * @extends Object
     * @param jobId {Number} 
     * @param action {String} 
     */
    constructor(jobId, action) { 
        
        JobChange.initialize(this, jobId, action);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, jobId, action) { 
        obj['job_id'] = jobId;
        obj['action'] = action;
    }

    /**
     * Constructs a <code>JobChange</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobChange} obj Optional instance to populate.
     * @return {module:model/JobChange} The populated <code>JobChange</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobChange();

            ApiClient.constructFromObject(data, obj, 'Object');
            

            if (data.hasOwnProperty('job_id')) {
                obj['job_id'] = ApiClient.convertToType(data['job_id'], 'Number');
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JobChange</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobChange</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JobChange.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }

        return true;
    }


}

JobChange.RequiredProperties = ["job_id", "action"];

/**
 * @member {Number} job_id
 */
JobChange.prototype['job_id'] = undefined;

/**
 * @member {String} action
 */
JobChange.prototype['action'] = undefined;






export default JobChange;

