/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CIMeasurement from '../model/CIMeasurement';
import CIMeasurementOld from '../model/CIMeasurementOld';
import HTTPValidationError from '../model/HTTPValidationError';
import JobChange from '../model/JobChange';
import Software from '../model/Software';
import UserSetting from '../model/UserSetting';

/**
* Default service.
* @module api/DefaultApi
* @version 0.1.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Compare In Repo
     * @param {String} ids 
     * @param {Object} opts Optional parameters
     * @param {String} [forceMode] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    compareInRepoV1CompareGetWithHttpInfo(ids, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'ids' is set
      if (ids === undefined || ids === null) {
        throw new Error("Missing the required parameter 'ids' when calling compareInRepoV1CompareGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'ids': ids,
        'force_mode': opts['forceMode']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/compare', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Compare In Repo
     * @param {String} ids 
     * @param {Object} opts Optional parameters
     * @param {String} opts.forceMode 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    compareInRepoV1CompareGet(ids, opts) {
      return this.compareInRepoV1CompareGetWithHttpInfo(ids, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Diff
     * @param {String} ids 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    diffV1DiffGetWithHttpInfo(ids) {
      let postBody = null;
      // verify the required parameter 'ids' is set
      if (ids === undefined || ids === null) {
        throw new Error("Missing the required parameter 'ids' when calling diffV1DiffGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'ids': ids
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/diff', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Diff
     * @param {String} ids 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    diffV1DiffGet(ids) {
      return this.diffV1DiffGetWithHttpInfo(ids)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Badge Single
     * @param {String} runId 
     * @param {Object} opts Optional parameters
     * @param {String} [metric = 'cpu_energy_rapl_msr_component')] 
     * @param {String} [unit = 'watt-hours')] 
     * @param {String} [phase] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getBadgeSingleV1BadgeSingleRunIdGetWithHttpInfo(runId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'runId' is set
      if (runId === undefined || runId === null) {
        throw new Error("Missing the required parameter 'runId' when calling getBadgeSingleV1BadgeSingleRunIdGet");
      }

      let pathParams = {
        'run_id': runId
      };
      let queryParams = {
        'metric': opts['metric'],
        'unit': opts['unit'],
        'phase': opts['phase']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/badge/single/{run_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Badge Single
     * @param {String} runId 
     * @param {Object} opts Optional parameters
     * @param {String} opts.metric  (default to 'cpu_energy_rapl_msr_component')
     * @param {String} opts.unit  (default to 'watt-hours')
     * @param {String} opts.phase 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getBadgeSingleV1BadgeSingleRunIdGet(runId, opts) {
      return this.getBadgeSingleV1BadgeSingleRunIdGetWithHttpInfo(runId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Ci Badge Get
     * @param {String} repo 
     * @param {String} branch 
     * @param {String} workflow 
     * @param {Object} opts Optional parameters
     * @param {String} [mode = 'last')] 
     * @param {String} [metric = 'energy')] 
     * @param {Number} [durationDays] 
     * @param {String} [unit = 'watt-hours')] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getCiBadgeGetV1CiBadgeGetGetWithHttpInfo(repo, branch, workflow, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getCiBadgeGetV1CiBadgeGetGet");
      }
      // verify the required parameter 'branch' is set
      if (branch === undefined || branch === null) {
        throw new Error("Missing the required parameter 'branch' when calling getCiBadgeGetV1CiBadgeGetGet");
      }
      // verify the required parameter 'workflow' is set
      if (workflow === undefined || workflow === null) {
        throw new Error("Missing the required parameter 'workflow' when calling getCiBadgeGetV1CiBadgeGetGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'repo': repo,
        'branch': branch,
        'workflow': workflow,
        'mode': opts['mode'],
        'metric': opts['metric'],
        'duration_days': opts['durationDays'],
        'unit': opts['unit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/ci/badge/get', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Ci Badge Get
     * @param {String} repo 
     * @param {String} branch 
     * @param {String} workflow 
     * @param {Object} opts Optional parameters
     * @param {String} opts.mode  (default to 'last')
     * @param {String} opts.metric  (default to 'energy')
     * @param {Number} opts.durationDays 
     * @param {String} opts.unit  (default to 'watt-hours')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getCiBadgeGetV1CiBadgeGetGet(repo, branch, workflow, opts) {
      return this.getCiBadgeGetV1CiBadgeGetGetWithHttpInfo(repo, branch, workflow, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Ci Badge Get
     * @param {String} repo 
     * @param {String} branch 
     * @param {String} workflow 
     * @param {Object} opts Optional parameters
     * @param {String} [mode = 'last')] 
     * @param {String} [metric = 'energy')] 
     * @param {Number} [durationDays] 
     * @param {String} [unit = 'watt-hours')] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getCiBadgeGetV1CiBadgeGetHeadWithHttpInfo(repo, branch, workflow, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getCiBadgeGetV1CiBadgeGetHead");
      }
      // verify the required parameter 'branch' is set
      if (branch === undefined || branch === null) {
        throw new Error("Missing the required parameter 'branch' when calling getCiBadgeGetV1CiBadgeGetHead");
      }
      // verify the required parameter 'workflow' is set
      if (workflow === undefined || workflow === null) {
        throw new Error("Missing the required parameter 'workflow' when calling getCiBadgeGetV1CiBadgeGetHead");
      }

      let pathParams = {
      };
      let queryParams = {
        'repo': repo,
        'branch': branch,
        'workflow': workflow,
        'mode': opts['mode'],
        'metric': opts['metric'],
        'duration_days': opts['durationDays'],
        'unit': opts['unit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/ci/badge/get', 'HEAD',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Ci Badge Get
     * @param {String} repo 
     * @param {String} branch 
     * @param {String} workflow 
     * @param {Object} opts Optional parameters
     * @param {String} opts.mode  (default to 'last')
     * @param {String} opts.metric  (default to 'energy')
     * @param {Number} opts.durationDays 
     * @param {String} opts.unit  (default to 'watt-hours')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getCiBadgeGetV1CiBadgeGetHead(repo, branch, workflow, opts) {
      return this.getCiBadgeGetV1CiBadgeGetHeadWithHttpInfo(repo, branch, workflow, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Ci Measurements
     * @param {String} repo 
     * @param {String} branch 
     * @param {String} workflow 
     * @param {Date} startDate 
     * @param {Date} endDate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getCiMeasurementsV1CiMeasurementsGetWithHttpInfo(repo, branch, workflow, startDate, endDate) {
      let postBody = null;
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getCiMeasurementsV1CiMeasurementsGet");
      }
      // verify the required parameter 'branch' is set
      if (branch === undefined || branch === null) {
        throw new Error("Missing the required parameter 'branch' when calling getCiMeasurementsV1CiMeasurementsGet");
      }
      // verify the required parameter 'workflow' is set
      if (workflow === undefined || workflow === null) {
        throw new Error("Missing the required parameter 'workflow' when calling getCiMeasurementsV1CiMeasurementsGet");
      }
      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling getCiMeasurementsV1CiMeasurementsGet");
      }
      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling getCiMeasurementsV1CiMeasurementsGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'repo': repo,
        'branch': branch,
        'workflow': workflow,
        'start_date': startDate,
        'end_date': endDate
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/ci/measurements', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Ci Measurements
     * @param {String} repo 
     * @param {String} branch 
     * @param {String} workflow 
     * @param {Date} startDate 
     * @param {Date} endDate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getCiMeasurementsV1CiMeasurementsGet(repo, branch, workflow, startDate, endDate) {
      return this.getCiMeasurementsV1CiMeasurementsGetWithHttpInfo(repo, branch, workflow, startDate, endDate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Ci Repositories
     * @param {Object} opts Optional parameters
     * @param {String} [repo] 
     * @param {String} [sortBy = 'name')] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getCiRepositoriesV1CiRepositoriesGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'repo': opts['repo'],
        'sort_by': opts['sortBy']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/ci/repositories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Ci Repositories
     * @param {Object} opts Optional parameters
     * @param {String} opts.repo 
     * @param {String} opts.sortBy  (default to 'name')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getCiRepositoriesV1CiRepositoriesGet(opts) {
      return this.getCiRepositoriesV1CiRepositoriesGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Ci Runs
     * @param {String} repo 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getCiRunsV1CiRunsGetWithHttpInfo(repo) {
      let postBody = null;
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getCiRunsV1CiRunsGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'repo': repo
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/ci/runs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Ci Runs
     * @param {String} repo 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getCiRunsV1CiRunsGet(repo) {
      return this.getCiRunsV1CiRunsGetWithHttpInfo(repo)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Ci Stats
     * @param {String} repo 
     * @param {String} branch 
     * @param {String} workflow 
     * @param {Date} startDate 
     * @param {Date} endDate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getCiStatsV1CiStatsGetWithHttpInfo(repo, branch, workflow, startDate, endDate) {
      let postBody = null;
      // verify the required parameter 'repo' is set
      if (repo === undefined || repo === null) {
        throw new Error("Missing the required parameter 'repo' when calling getCiStatsV1CiStatsGet");
      }
      // verify the required parameter 'branch' is set
      if (branch === undefined || branch === null) {
        throw new Error("Missing the required parameter 'branch' when calling getCiStatsV1CiStatsGet");
      }
      // verify the required parameter 'workflow' is set
      if (workflow === undefined || workflow === null) {
        throw new Error("Missing the required parameter 'workflow' when calling getCiStatsV1CiStatsGet");
      }
      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling getCiStatsV1CiStatsGet");
      }
      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling getCiStatsV1CiStatsGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'repo': repo,
        'branch': branch,
        'workflow': workflow,
        'start_date': startDate,
        'end_date': endDate
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/ci/stats', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Ci Stats
     * @param {String} repo 
     * @param {String} branch 
     * @param {String} workflow 
     * @param {Date} startDate 
     * @param {Date} endDate 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getCiStatsV1CiStatsGet(repo, branch, workflow, startDate, endDate) {
      return this.getCiStatsV1CiStatsGetWithHttpInfo(repo, branch, workflow, startDate, endDate)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Insights
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getInsightsV1CiInsightsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/ci/insights', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Insights
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getInsightsV1CiInsightsGet() {
      return this.getInsightsV1CiInsightsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Insights
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getInsightsV1InsightsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/insights', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Insights
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getInsightsV1InsightsGet() {
      return this.getInsightsV1InsightsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Jobs
     * @param {Object} opts Optional parameters
     * @param {Number} [machineId] 
     * @param {String} [state] 
     * @param {Number} [jobId] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getJobsV2JobsGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'machine_id': opts['machineId'],
        'state': opts['state'],
        'job_id': opts['jobId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v2/jobs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Jobs
     * @param {Object} opts Optional parameters
     * @param {Number} opts.machineId 
     * @param {String} opts.state 
     * @param {Number} opts.jobId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getJobsV2JobsGet(opts) {
      return this.getJobsV2JobsGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Machines
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getMachinesV1MachinesGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/machines', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Machines
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getMachinesV1MachinesGet() {
      return this.getMachinesV1MachinesGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Measurements Single
     * @param {String} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getMeasurementsSingleV1MeasurementsSingleRunIdGetWithHttpInfo(runId) {
      let postBody = null;
      // verify the required parameter 'runId' is set
      if (runId === undefined || runId === null) {
        throw new Error("Missing the required parameter 'runId' when calling getMeasurementsSingleV1MeasurementsSingleRunIdGet");
      }

      let pathParams = {
        'run_id': runId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/measurements/single/{run_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Measurements Single
     * @param {String} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getMeasurementsSingleV1MeasurementsSingleRunIdGet(runId) {
      return this.getMeasurementsSingleV1MeasurementsSingleRunIdGetWithHttpInfo(runId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Network
     * @param {Object} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getNetworkV1NetworkRunIdGetWithHttpInfo(runId) {
      let postBody = null;
      // verify the required parameter 'runId' is set
      if (runId === undefined || runId === null) {
        throw new Error("Missing the required parameter 'runId' when calling getNetworkV1NetworkRunIdGet");
      }

      let pathParams = {
        'run_id': runId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/network/{run_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Network
     * @param {Object} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getNetworkV1NetworkRunIdGet(runId) {
      return this.getNetworkV1NetworkRunIdGetWithHttpInfo(runId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Notes
     * @param {Object} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getNotesV1NotesRunIdGetWithHttpInfo(runId) {
      let postBody = null;
      // verify the required parameter 'runId' is set
      if (runId === undefined || runId === null) {
        throw new Error("Missing the required parameter 'runId' when calling getNotesV1NotesRunIdGet");
      }

      let pathParams = {
        'run_id': runId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/notes/{run_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Notes
     * @param {Object} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getNotesV1NotesRunIdGet(runId) {
      return this.getNotesV1NotesRunIdGetWithHttpInfo(runId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Optimizations
     * @param {String} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getOptimizationsV1OptimizationsRunIdGetWithHttpInfo(runId) {
      let postBody = null;
      // verify the required parameter 'runId' is set
      if (runId === undefined || runId === null) {
        throw new Error("Missing the required parameter 'runId' when calling getOptimizationsV1OptimizationsRunIdGet");
      }

      let pathParams = {
        'run_id': runId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/optimizations/{run_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Optimizations
     * @param {String} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getOptimizationsV1OptimizationsRunIdGet(runId) {
      return this.getOptimizationsV1OptimizationsRunIdGetWithHttpInfo(runId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Phase Stats Single
     * @param {String} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getPhaseStatsSingleV1PhaseStatsSingleRunIdGetWithHttpInfo(runId) {
      let postBody = null;
      // verify the required parameter 'runId' is set
      if (runId === undefined || runId === null) {
        throw new Error("Missing the required parameter 'runId' when calling getPhaseStatsSingleV1PhaseStatsSingleRunIdGet");
      }

      let pathParams = {
        'run_id': runId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/phase_stats/single/{run_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Phase Stats Single
     * @param {String} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getPhaseStatsSingleV1PhaseStatsSingleRunIdGet(runId) {
      return this.getPhaseStatsSingleV1PhaseStatsSingleRunIdGetWithHttpInfo(runId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Repositories
     * @param {Object} opts Optional parameters
     * @param {String} [uri] 
     * @param {String} [branch] 
     * @param {Number} [machineId] 
     * @param {String} [machine] 
     * @param {String} [filename] 
     * @param {String} [sortBy = 'name')] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getRepositoriesV1RepositoriesGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'uri': opts['uri'],
        'branch': opts['branch'],
        'machine_id': opts['machineId'],
        'machine': opts['machine'],
        'filename': opts['filename'],
        'sort_by': opts['sortBy']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/repositories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Repositories
     * @param {Object} opts Optional parameters
     * @param {String} opts.uri 
     * @param {String} opts.branch 
     * @param {Number} opts.machineId 
     * @param {String} opts.machine 
     * @param {String} opts.filename 
     * @param {String} opts.sortBy  (default to 'name')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getRepositoriesV1RepositoriesGet(opts) {
      return this.getRepositoriesV1RepositoriesGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Run
     * @param {String} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getRunV2RunRunIdGetWithHttpInfo(runId) {
      let postBody = null;
      // verify the required parameter 'runId' is set
      if (runId === undefined || runId === null) {
        throw new Error("Missing the required parameter 'runId' when calling getRunV2RunRunIdGet");
      }

      let pathParams = {
        'run_id': runId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v2/run/{run_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Run
     * @param {String} runId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getRunV2RunRunIdGet(runId) {
      return this.getRunV2RunRunIdGetWithHttpInfo(runId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Runs
     * @param {Object} opts Optional parameters
     * @param {String} [uri] 
     * @param {String} [branch] 
     * @param {Number} [machineId] 
     * @param {String} [machine] 
     * @param {String} [filename] 
     * @param {Number} [jobId] 
     * @param {Boolean} [failed] 
     * @param {Number} [limit] 
     * @param {Object} [uriMode] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getRunsV2RunsGetWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'uri': opts['uri'],
        'branch': opts['branch'],
        'machine_id': opts['machineId'],
        'machine': opts['machine'],
        'filename': opts['filename'],
        'job_id': opts['jobId'],
        'failed': opts['failed'],
        'limit': opts['limit'],
        'uri_mode': opts['uriMode']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v2/runs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Runs
     * @param {Object} opts Optional parameters
     * @param {String} opts.uri 
     * @param {String} opts.branch 
     * @param {Number} opts.machineId 
     * @param {String} opts.machine 
     * @param {String} opts.filename 
     * @param {Number} opts.jobId 
     * @param {Boolean} opts.failed 
     * @param {Number} opts.limit 
     * @param {Object} opts.uriMode 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getRunsV2RunsGet(opts) {
      return this.getRunsV2RunsGetWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Timeline Badge
     * @param {String} metric 
     * @param {String} uri 
     * @param {Object} opts Optional parameters
     * @param {String} [detailName] 
     * @param {Number} [machineId] 
     * @param {String} [branch] 
     * @param {String} [filename] 
     * @param {String} [unit = 'watt-hours')] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getTimelineBadgeV1BadgeTimelineGetWithHttpInfo(metric, uri, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'metric' is set
      if (metric === undefined || metric === null) {
        throw new Error("Missing the required parameter 'metric' when calling getTimelineBadgeV1BadgeTimelineGet");
      }
      // verify the required parameter 'uri' is set
      if (uri === undefined || uri === null) {
        throw new Error("Missing the required parameter 'uri' when calling getTimelineBadgeV1BadgeTimelineGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'metric': metric,
        'uri': uri,
        'detail_name': opts['detailName'],
        'machine_id': opts['machineId'],
        'branch': opts['branch'],
        'filename': opts['filename'],
        'unit': opts['unit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/badge/timeline', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Timeline Badge
     * @param {String} metric 
     * @param {String} uri 
     * @param {Object} opts Optional parameters
     * @param {String} opts.detailName 
     * @param {Number} opts.machineId 
     * @param {String} opts.branch 
     * @param {String} opts.filename 
     * @param {String} opts.unit  (default to 'watt-hours')
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getTimelineBadgeV1BadgeTimelineGet(metric, uri, opts) {
      return this.getTimelineBadgeV1BadgeTimelineGetWithHttpInfo(metric, uri, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Timeline Stats
     * @param {String} uri 
     * @param {Number} machineId 
     * @param {Object} opts Optional parameters
     * @param {String} [branch] 
     * @param {String} [filename] 
     * @param {Date} [startDate] 
     * @param {Date} [endDate] 
     * @param {String} [metric] 
     * @param {String} [phase] 
     * @param {String} [sorting] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getTimelineStatsV1TimelineGetWithHttpInfo(uri, machineId, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'uri' is set
      if (uri === undefined || uri === null) {
        throw new Error("Missing the required parameter 'uri' when calling getTimelineStatsV1TimelineGet");
      }
      // verify the required parameter 'machineId' is set
      if (machineId === undefined || machineId === null) {
        throw new Error("Missing the required parameter 'machineId' when calling getTimelineStatsV1TimelineGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'uri': uri,
        'machine_id': machineId,
        'branch': opts['branch'],
        'filename': opts['filename'],
        'start_date': opts['startDate'],
        'end_date': opts['endDate'],
        'metric': opts['metric'],
        'phase': opts['phase'],
        'sorting': opts['sorting']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/timeline', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Timeline Stats
     * @param {String} uri 
     * @param {Number} machineId 
     * @param {Object} opts Optional parameters
     * @param {String} opts.branch 
     * @param {String} opts.filename 
     * @param {Date} opts.startDate 
     * @param {Date} opts.endDate 
     * @param {String} opts.metric 
     * @param {String} opts.phase 
     * @param {String} opts.sorting 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getTimelineStatsV1TimelineGet(uri, machineId, opts) {
      return this.getTimelineStatsV1TimelineGetWithHttpInfo(uri, machineId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get User Settings
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getUserSettingsV1UserSettingsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/user/settings', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get User Settings
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getUserSettingsV1UserSettingsGet() {
      return this.getUserSettingsV1UserSettingsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get Watchlist
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    getWatchlistV1WatchlistGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/watchlist', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get Watchlist
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    getWatchlistV1WatchlistGet() {
      return this.getWatchlistV1WatchlistGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Home
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    homeGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Home
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    homeGet() {
      return this.homeGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Old V1 Jobs Endpoint
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    oldV1JobsEndpointV1JobsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/jobs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Old V1 Jobs Endpoint
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    oldV1JobsEndpointV1JobsGet() {
      return this.oldV1JobsEndpointV1JobsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Old V1 Run Endpoint
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    oldV1RunEndpointV1RunRunIdGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/run/{run_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Old V1 Run Endpoint
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    oldV1RunEndpointV1RunRunIdGet() {
      return this.oldV1RunEndpointV1RunRunIdGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Old V1 Runs Endpoint
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    oldV1RunsEndpointV1RunsGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/runs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Old V1 Runs Endpoint
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    oldV1RunsEndpointV1RunsGet() {
      return this.oldV1RunsEndpointV1RunsGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Post Ci Measurement Add Deprecated
     * @param {module:model/CIMeasurementOld} cIMeasurementOld 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    postCiMeasurementAddDeprecatedV1CiMeasurementAddPostWithHttpInfo(cIMeasurementOld) {
      let postBody = cIMeasurementOld;
      // verify the required parameter 'cIMeasurementOld' is set
      if (cIMeasurementOld === undefined || cIMeasurementOld === null) {
        throw new Error("Missing the required parameter 'cIMeasurementOld' when calling postCiMeasurementAddDeprecatedV1CiMeasurementAddPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/ci/measurement/add', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Post Ci Measurement Add Deprecated
     * @param {module:model/CIMeasurementOld} cIMeasurementOld 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    postCiMeasurementAddDeprecatedV1CiMeasurementAddPost(cIMeasurementOld) {
      return this.postCiMeasurementAddDeprecatedV1CiMeasurementAddPostWithHttpInfo(cIMeasurementOld)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Post Ci Measurement Add
     * @param {module:model/CIMeasurement} cIMeasurement 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    postCiMeasurementAddV2CiMeasurementAddPostWithHttpInfo(cIMeasurement) {
      let postBody = cIMeasurement;
      // verify the required parameter 'cIMeasurement' is set
      if (cIMeasurement === undefined || cIMeasurement === null) {
        throw new Error("Missing the required parameter 'cIMeasurement' when calling postCiMeasurementAddV2CiMeasurementAddPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v2/ci/measurement/add', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Post Ci Measurement Add
     * @param {module:model/CIMeasurement} cIMeasurement 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    postCiMeasurementAddV2CiMeasurementAddPost(cIMeasurement) {
      return this.postCiMeasurementAddV2CiMeasurementAddPostWithHttpInfo(cIMeasurement)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Robots Txt
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    robotsTxtRobotsTxtGetWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/robots.txt', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Robots Txt
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    robotsTxtRobotsTxtGet() {
      return this.robotsTxtRobotsTxtGetWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Software Add
     * @param {module:model/Software} software 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    softwareAddV1SoftwareAddPostWithHttpInfo(software) {
      let postBody = software;
      // verify the required parameter 'software' is set
      if (software === undefined || software === null) {
        throw new Error("Missing the required parameter 'software' when calling softwareAddV1SoftwareAddPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/software/add', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Software Add
     * @param {module:model/Software} software 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    softwareAddV1SoftwareAddPost(software) {
      return this.softwareAddV1SoftwareAddPostWithHttpInfo(software)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update Job
     * @param {module:model/JobChange} jobChange 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    updateJobV1JobPutWithHttpInfo(jobChange) {
      let postBody = jobChange;
      // verify the required parameter 'jobChange' is set
      if (jobChange === undefined || jobChange === null) {
        throw new Error("Missing the required parameter 'jobChange' when calling updateJobV1JobPut");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/job', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update Job
     * @param {module:model/JobChange} jobChange 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    updateJobV1JobPut(jobChange) {
      return this.updateJobV1JobPutWithHttpInfo(jobChange)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update User Setting
     * @param {module:model/UserSetting} userSetting 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    updateUserSettingV1UserSettingPutWithHttpInfo(userSetting) {
      let postBody = userSetting;
      // verify the required parameter 'userSetting' is set
      if (userSetting === undefined || userSetting === null) {
        throw new Error("Missing the required parameter 'userSetting' when calling updateUserSettingV1UserSettingPut");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Header'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/user/setting', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update User Setting
     * @param {module:model/UserSetting} userSetting 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    updateUserSettingV1UserSettingPut(userSetting) {
      return this.updateUserSettingV1UserSettingPutWithHttpInfo(userSetting)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
