name: Daily Test Run - Bare Metal - Dev Branch
run-name: Scheduled - ${{ github.ref_name }}
on:
  schedule:
    - cron: '0 0 * * *'
  #push:
  #  branch: test-pipeline-improvements
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      recent_dev_commit: ${{ steps.check_dev_commits.outputs.recent_commit }}
    steps:
      - id: check_dev_commits
        uses: green-coding-berlin/eco-ci-activity-checker@main
        with:
         repo: 'green-coding-berlin/green-metrics-tool'
         branch: 'dev'
  run-tests-dev:
    needs: check_date
    if: ${{ needs.check_date.outputs.recent_dev_commit == 'true' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'dev'
          submodules: 'true'
      
      - name: 'Setup, Run, and Teardown Tests'
        uses: ./.github/actions/gmt-pytest
        with:
           metrics-to-turn-off: 'System Sensors Debug'